# Generated by Django 3.2.9 on 2021-11-08 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_auto_20211101_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.CharField(max_length=200),
        ),
    ]
