# Generated by Django 3.2.8 on 2021-11-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_auto_20211120_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='book_title',
        ),
        migrations.AddField(
            model_name='post',
            name='room_id',
            field=models.IntegerField(default=-1),
        ),
    ]
