# Generated by Django 3.2.8 on 2021-10-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_post_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
