# Generated by Django 3.2.8 on 2021-11-01 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookclub', '0003_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_title',
            field=models.CharField(default='DefaultTitle', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_description', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=50)),
                ('book_cover', models.FileField(blank=True, upload_to='')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
